Fix build failures with standard C 2023.
As initially identified in [Debian bug #1097250], PGPLOT is affected
by build failures caused by mismatching prototypes with Gcc 15:

	In file included from PGPLOT.xs:16:
	pgfun.c: In function ‘pgfun1’:
	pgfun.c:78:7: warning: old-style function definition [-Wold-style-definition]
	   78 | float pgfun1(x)
	      |       ^~~~~~
	pgfun.c:79:4: error: number of arguments doesn’t match prototype
	   79 |    float *x; {
	      |    ^~~~~
	pgfun.c:29:7: error: prototype declaration
	   29 | float pgfun1();
	      |       ^~~~~~
	pgfun.c: In function ‘pgfun2’:
	pgfun.c:120:7: warning: old-style function definition [-Wold-style-definition]
	  120 | float pgfun2(x)
	      |       ^~~~~~
	pgfun.c:121:4: error: number of arguments doesn’t match prototype
	  121 |    float *x; {
	      |    ^~~~~
	pgfun.c:30:7: error: prototype declaration
	   30 | float pgfun2();
	      |       ^~~~~~
	pgfun.c: In function ‘pgfunplot’:
	pgfun.c:161:6: warning: old-style function definition [-Wold-style-definition]
	  161 | void pgfunplot(visible,x,y,z)
	      |      ^~~~~~~~~
	pgfun.c:163:4: error: number of arguments doesn’t match prototype
	  163 |    float *x,*y,*z; {
	      |    ^~~~~
	pgfun.c:31:8: error: prototype declaration
	   31 | void   pgfunplot();
	      |        ^~~~~~~~~

This patch adds missing function argument types in prototypes, and
casts a couple of indirect function calls, to ensure compatibility
with the standard C 2023, now selected by default by gcc 15 and later.

[Debian bug #1097250]: https://bugs.debian.org/cgi-bin/bugreport.cgi?bug=1097250

Signed-off-by: Étienne Mollier <emollier@debian.org>